export const mockMeritStudents = [
  {
    id: "st-001",
    name: "Arafat Rahman",
    roll: "WR-001",
    marks: 82,
    marksPublished: true,
    teacher: "Nusrat Jahan",
    submissions: ["page-1.jpg", "page-2.jpg"],
    teacherUploads: ["checked-page-1.jpg", "checked-page-2.jpg"],
  },
  {
    id: "st-002",
    name: "Maliha Karim",
    roll: "WR-002",
    marks: 76,
    marksPublished: true,
    teacher: "Nusrat Jahan",
    submissions: ["answer-sheet.pdf"],
    teacherUploads: ["evaluated-answer.pdf"],
  },
  {
    id: "st-003",
    name: "Siam Chowdhury",
    roll: "WR-003",
    marks: null,
    marksPublished: false,
    teacher: "Rezaul Islam",
    submissions: ["page-1.jpg", "page-2.jpg", "page-3.jpg"],
    teacherUploads: [],
  },
  {
    id: "st-004",
    name: "Tasnim Akter",
    roll: "WR-004",
    marks: 91,
    marksPublished: true,
    teacher: "Rezaul Islam",
    submissions: ["answer-booklet.pdf"],
    teacherUploads: ["marked-booklet.pdf"],
  },
  {
    id: "st-005",
    name: "Nafis Hasan",
    roll: "WR-005",
    marks: null,
    marksPublished: false,
    teacher: "Farhana Sultana",
    submissions: ["page-1.png"],
    teacherUploads: [],
  },
  {
    id: "st-006",
    name: "Jannatul Ferdous",
    roll: "WR-006",
    marks: 68,
    marksPublished: true,
    teacher: "Farhana Sultana",
    submissions: ["answer-set.pdf"],
    teacherUploads: ["checked-answer-set.pdf"],
  },
];
